FROM alpine:latest

RUN apk -U add \
    py2-pip py2-requests py2-yaml

# Install the CI scripts
ADD . /usr/src/wordpress-cd-rancher
WORKDIR /usr/src/wordpress-cd-rancher
RUN pip install -r requirements.txt

